/*
 * Biofeedback
 * This a documentation for the biofeedback Rest API 
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aut.presentationskills.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * DeckUpdate
 */
public class DeckUpdate {

  @SerializedName("title")
  private String title = null;

  @SerializedName("imagePaths")
  private List<String> imagePaths = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("type")
  private String type = null;
  public DeckUpdate title(String title) {
    this.title = title;
    return this;
  }

  

  /**
  * Get title
  * @return title
  **/
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }
  public DeckUpdate imagePaths(List<String> imagePaths) {
    this.imagePaths = imagePaths;
    return this;
  }

  public DeckUpdate addImagePathsItem(String imagePathsItem) {
    if (this.imagePaths == null) {
      this.imagePaths = new ArrayList<String>();
    }
    this.imagePaths.add(imagePathsItem);
    return this;
  }

  /**
  * Get imagePaths
  * @return imagePaths
  **/
  public List<String> getImagePaths() {
    return imagePaths;
  }
  public void setImagePaths(List<String> imagePaths) {
    this.imagePaths = imagePaths;
  }
  public DeckUpdate description(String description) {
    this.description = description;
    return this;
  }

  

  /**
  * Get description
  * @return description
  **/
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  public DeckUpdate type(String type) {
    this.type = type;
    return this;
  }

  

  /**
  * Get type
  * @return type
  **/
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeckUpdate deckUpdate = (DeckUpdate) o;
    return Objects.equals(this.title, deckUpdate.title) &&
        Objects.equals(this.imagePaths, deckUpdate.imagePaths) &&
        Objects.equals(this.description, deckUpdate.description) &&
        Objects.equals(this.type, deckUpdate.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, imagePaths, description, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeckUpdate {\n");

    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    imagePaths: ").append(toIndentedString(imagePaths)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
