/*
 * Biofeedback
 * This a documentation for the biofeedback Rest API 
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aut.presentationskills.model;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Measurement
 */
public class Measurement {

  @SerializedName("_id")
  @Expose
  private String _id = null;

  @SerializedName("subjectId")
  @Expose
  private String subjectId = null;

  @SerializedName("measurementDate")
  @Expose
  private String measurementDate = null;

  @SerializedName("description")
  @Expose
  private String description = null;

  @SerializedName("title")
  @Expose
  private String title = null;

  @SerializedName("createdAt")
  @Expose
  private String createdAt = null;

  @SerializedName("status")
  @Expose
  private MeasurementStatus status = null;

  @SerializedName("scene")
  @Expose
  private Scene scene = null;

  @SerializedName("decks")
  @Expose
  private List<Deck> decks = null;
  public Measurement _id(String _id) {
    this._id = _id;
    return this;
  }

  

  /**
  * Get _id
  * @return _id
  **/
  public String getId() {
    return _id;
  }
  public void setId(String _id) {
    this._id = _id;
  }

  /**
  * Get subjectId
  * @return subjectId
  **/
  public String getSubjectId() {
    return subjectId;
  }
  public void setSubjectId(String subjectId) {
    this.subjectId = subjectId;
  }

  /**
  * Get measurementDate
  * @return measurementDate
  **/
  public String getMeasurementDate() {
    return measurementDate;
  }
  public void setMeasurementDate(String measurementDate) {
    this.measurementDate = measurementDate;
  }

  /**
  * Get description
  * @return description
  **/
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
  * Get title
  * @return title
  **/
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
  * Get createdAt
  * @return createdAt
  **/
  public String getCreatedAt() {
    return createdAt;
  }
  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  /**
  * Get status
  * @return status
  **/
  public MeasurementStatus getStatus() {
    return status;
  }
  public void setStatus(MeasurementStatus status) {
    this.status = status;
  }

  /**
  * Get scene
  * @return scene
  **/
  public Scene getScene() {
    return scene;
  }
  public void setScene(Scene scene) {
    this.scene = scene;
  }

  public Measurement addDecksItem(Deck decksItem) {
    if (this.decks == null) {
      this.decks = new ArrayList<Deck>();
    }
    this.decks.add(decksItem);
    return this;
  }

  /**
  * Get decks
  * @return decks
  **/
  public List<Deck> getDecks() {
    return decks;
  }
  public void setDecks(List<Deck> decks) {
    this.decks = decks;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Measurement measurement = (Measurement) o;
    return Objects.equals(this._id, measurement._id) &&
        Objects.equals(this.subjectId, measurement.subjectId) &&
        Objects.equals(this.measurementDate, measurement.measurementDate) &&
        Objects.equals(this.description, measurement.description) &&
        Objects.equals(this.title, measurement.title) &&
        Objects.equals(this.createdAt, measurement.createdAt) &&
        Objects.equals(this.status, measurement.status) &&
        Objects.equals(this.scene, measurement.scene) &&
        Objects.equals(this.decks, measurement.decks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, subjectId, measurementDate, description, title, createdAt, status, scene, decks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Measurement {\n");

    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    subjectId: ").append(toIndentedString(subjectId)).append("\n");
    sb.append("    measurementDate: ").append(toIndentedString(measurementDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    scene: ").append(toIndentedString(scene)).append("\n");
    sb.append("    decks: ").append(toIndentedString(decks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
