/*
 * Biofeedback
 * This a documentation for the biofeedback Rest API 
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aut.presentationskills.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MeasurementData
 */

public class MeasurementData {

  @SerializedName("_id")
  private String _id = null;

  @SerializedName("measurementId")
  private String measurementId = null;

  @SerializedName("timestamp")
  private String timestamp = null;

  @SerializedName("data")
  private List<MeasurementDataData> data = null;
  public MeasurementData _id(String _id) {
    this._id = _id;
    return this;
  }

  

  /**
  * Get _id
  * @return _id
  **/
  public String getId() {
    return _id;
  }
  public void setId(String _id) {
    this._id = _id;
  }

  /**
  * Get measurementId
  * @return measurementId
  **/
  public String getMeasurementId() {
    return measurementId;
  }
  public void setMeasurementId(String measurementId) {
    this.measurementId = measurementId;
  }

    /**
  * Get timestamp
  * @return timestamp
  **/
  public String getTimestamp() {
    return timestamp;
  }
  public void setTimestamp(String timestamp) {
    this.timestamp = timestamp;
  }

  public MeasurementData addDataItem(MeasurementDataData dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<MeasurementDataData>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
  * Get data
  * @return data
  **/
  public List<MeasurementDataData> getData() {
    return data;
  }
  public void setData(List<MeasurementDataData> data) {
    this.data = data;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeasurementData measurementData = (MeasurementData) o;
    return Objects.equals(this._id, measurementData._id) &&
        Objects.equals(this.measurementId, measurementData.measurementId) &&
        Objects.equals(this.timestamp, measurementData.timestamp) &&
        Objects.equals(this.data, measurementData.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, measurementId, timestamp, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeasurementData {\n");

    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    measurementId: ").append(toIndentedString(measurementId)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
