/*
 * Biofeedback
 * This a documentation for the biofeedback Rest API 
 *
 * OpenAPI spec version: 1.0.0-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.aut.presentationskills.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * VideoUpdate
 */
public class VideoUpdate {

  @SerializedName("name")
  private String name = null;

  @SerializedName("videoUrl")
  private String videoUrl = null;

  @SerializedName("labels")
  private List<VideoLabels> labels = null;
  public VideoUpdate name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
  * Get videoUrl
  * @return videoUrl
  **/
  public String getVideoUrl() {
    return videoUrl;
  }
  public void setVideoUrl(String videoUrl) {
    this.videoUrl = videoUrl;
  }

  public VideoUpdate addLabelsItem(VideoLabels labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<VideoLabels>();
    }
    this.labels.add(labelsItem);
    return this;
  }

  /**
  * Get labels
  * @return labels
  **/
  public List<VideoLabels> getLabels() {
    return labels;
  }
  public void setLabels(List<VideoLabels> labels) {
    this.labels = labels;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VideoUpdate videoUpdate = (VideoUpdate) o;
    return Objects.equals(this.name, videoUpdate.name) &&
        Objects.equals(this.videoUrl, videoUpdate.videoUrl) &&
        Objects.equals(this.labels, videoUpdate.labels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, videoUrl, labels);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VideoUpdate {\n");

    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    videoUrl: ").append(toIndentedString(videoUrl)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
